// Sample tirth data - to be replaced with real API calls
export const sampleTirths = [
  {
    id: 'palitana',
    name: 'Palitana',
    description:
      'The magnificent Palitana is one of the most holy pilgrimage sites for Jains, with over 900 temples carved from white stone.',
    historicalBackground:
      'Palitana has been a sacred pilgrimage site for thousands of years. The temples were built over several centuries, with the earliest temples dating back to the 11th century.',
    foundingYear: 1000,
    foundingDetails: 'Founded by Jain monks and later expanded by various kings and wealthy merchants',
    pratisthaYear: 1500,
    acharya: 'Various Acharyas',
    architecture:
      'The temples feature intricate marble carvings, grand domes, and beautiful sculptural details. The architectural style blends both Shwetambar and Digambar influences.',
    moolnayak: [
      {
        name: 'Adinath',
        height: '25 feet',
        metal: 'Gold and Silver',
        year: 1200,
        details: 'The main deity of Palitana',
      },
      {
        name: 'Vasupujya',
        height: '18 feet',
        metal: 'Silver',
        year: 1300,
        details: 'The 12th Tirthankara',
      },
    ],
    specialFacts: [
      '900+ temples on a single hill',
      'The temples are made entirely of marble',
      'The pilgrimage involves climbing 3,500 steps',
      'The temples are illuminated with beautiful lighting at night',
    ],
    poojaTimings: '6:00 AM - 10:00 PM',
    darshanTimings: '6:00 AM - 8:00 PM',
    festivals: [
      {
        name: 'Mahavir Jayanti',
        date: 'Chaitra Shukla 13',
        month: 'March-April',
        description: 'Celebration of Lord Mahavir\'s birth',
        specialEvent: 'Special pujas and processions',
      },
      {
        name: 'Diwali',
        date: 'Kartik Amavasya',
        month: 'October-November',
        description: 'Festival of lights',
        specialEvent: 'Oil lamps light up all temples',
      },
    ],
    location: {
      latitude: 22.128,
      longitude: 71.828,
      address: 'Palitana, Bhavnagar',
      city: 'Palitana',
      state: 'Gujarat',
      zipCode: '364270',
    },
    images: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1504681869696-d977211a0f4d?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1465014849957-b69a14ad6edf?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=600&h=400&fit=crop',
    ],
    sect: 'Shwetambar',
    type: 'Atishay-Kshetra',
    facilities: [
      {
        id: 'f1',
        name: 'Shri Krishna Bhojanshala',
        type: 'bhojanshala',
        description: 'Traditional vegetarian restaurant serving Gujarati cuisine',
        location: {
          latitude: 22.128,
          longitude: 71.828,
          address: 'Main Market, Palitana',
          city: 'Palitana',
          state: 'Gujarat',
        },
        contact: {
          phone: '+91-2848-252222',
          email: 'info@krishna-bhojanshala.com',
          website: 'www.krishna-bhojanshala.com',
        },
        image: 'https://via.placeholder.com/300x200?text=Bhojanshala',
        rating: 4.5,
        availability: 'Open daily',
        operatingHours: '12:00 PM - 10:00 PM',
      },
      {
        id: 'f2',
        name: 'Shanti Dharmashala',
        type: 'dharmashala',
        description: 'Budget-friendly accommodation for pilgrims',
        location: {
          latitude: 22.129,
          longitude: 71.829,
          address: 'Near Temple Gate, Palitana',
          city: 'Palitana',
          state: 'Gujarat',
        },
        contact: {
          phone: '+91-2848-252333',
          email: 'info@shanti-dharmashala.com',
        },
        image: 'https://via.placeholder.com/300x200?text=Dharmashala',
        rating: 4.2,
        availability: '50 rooms available',
        operatingHours: '24 hours',
      },
    ],
    rating: 4.8,
    reviews: 1250,
    travelDuration: '2-3 days',
  },
  {
    id: 'ranakpur',
    name: 'Ranakpur Jain Temple',
    description:
      'A stunning white marble temple complex with intricate carvings and vast courtyards, one of the five most important pilgrimage sites for Jains.',
    historicalBackground:
      'Built in the 15th century by the merchant Dhanraj Mandal, Ranakpur temple represents a masterpiece of Jain architecture.',
    foundingYear: 1440,
    foundingDetails: 'Constructed by the Jain merchant Dhanraj Mandal during the reign of Rana Kumbha',
    pratisthaYear: 1442,
    acharya: 'Sri Diji Maharaj',
    architecture:
      'The temple features 29 halls, 80 domes, and is supported by 1,444 marble pillars, each with unique carvings and designs.',
    moolnayak: [
      {
        name: 'Adinath',
        height: '20 feet',
        metal: 'White Marble',
        year: 1442,
        details: 'The main idol of the temple',
      },
    ],
    specialFacts: [
      '1,444 uniquely carved marble pillars',
      'Every pillar has different carving designs',
      'The temple is located at 2,585 feet altitude',
      'The sacred hill has caves used by ancient Jain monks',
    ],
    poojaTimings: '5:00 AM - 10:00 PM',
    darshanTimings: '5:00 AM - 9:00 PM',
    festivals: [
      {
        name: 'Kartik Purnima',
        date: 'Kartik Purnima',
        month: 'November',
        description: 'Full moon celebration',
      },
    ],
    location: {
      latitude: 25.05,
      longitude: 73.8,
      address: 'Ranakpur, Pali District',
      city: 'Ranakpur',
      state: 'Rajasthan',
      zipCode: '306703',
    },
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
    ],
    sect: 'Shwetambar',
    type: 'Gyan-sthan',
    facilities: [],
    rating: 4.7,
    reviews: 980,
    travelDuration: '1-2 days',
  },
  {
    id: 'manas-mandir',
    name: 'Manas Mandir',
    description: 'A revered Jain temple known for its serene atmosphere and active community rituals.',
    historicalBackground: 'Manas Mandir has been maintained by local Jain communities for centuries and serves as an important center for daily worship and festivals.',
    foundingYear: 1800,
    foundingDetails: 'Community-funded reconstruction and maintenance',
    pratisthaYear: 1820,
    acharya: 'Local Acharyas',
    architecture: 'A relatively modern temple with traditional motifs and a white marble sanctum.',
    moolnayak: [
      {
        name: 'Parshvanatha',
        height: '8 feet',
        metal: 'Marble',
        year: 1820,
        details: 'Main deity of the temple',
      },
    ],
    specialFacts: ['Active community kitchen', 'Regular festivals and satsangs', 'Accessible location'],
    poojaTimings: '5:30 AM - 9:30 PM',
    darshanTimings: '5:00 AM - 9:00 PM',
    festivals: [
      {
        name: 'Paryushan',
        date: 'Bhadrapada (varies)',
        month: 'August-September',
        description: 'An important Jain festival observed with great reverence',
      },
    ],
    location: {
      latitude: 25.0,
      longitude: 85.0,
      address: 'Manas Mandir Road',
      city: 'Gaya',
      state: 'Bihar',
      zipCode: '823001',
    },
    images: [
      'https://images.unsplash.com/photo-1504681869696-d977211a0f4d?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1465014849957-b69a14ad6edf?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1533462701944-a01f13c4c89f?w=600&h=400&fit=crop',
    ],
    sect: 'Shwetambar',
    type: 'Gyan-sthan',
    facilities: [],
    rating: 4.4,
    reviews: 210,
    travelDuration: '1 day',
  },
  {
    id: 'shikharji',
    name: 'Shikharji (Parasnath Hill)',
    description: 'One of the most sacred Jain pilgrimage sites, located on Parasnath Hill with numerous temples across the summit.',
    historicalBackground: 'Shikharji has been a major pilgrimage site for Jains for many centuries, with inscriptions and temples dating back several eras.',
    foundingYear: 1100,
    foundingDetails: 'Ancient sites with ongoing patronage',
    pratisthaYear: 1200,
    acharya: 'Various Acharyas',
    architecture: 'A collection of hilltop temples with stone and marble structures, often set among scenic vistas.',
    moolnayak: [
      {
        name: 'Multiple Tirthankaras',
        height: 'Varies',
        metal: 'Stone/Marble',
        year: 1200,
        details: 'Different temples have different moolnayaks',
      },
    ],
    specialFacts: ['Major Jain pilgrimage', 'Multiple temples across the hill', 'Annual large-scale yatras'],
    poojaTimings: '6:00 AM - 7:00 PM',
    darshanTimings: '6:00 AM - 6:00 PM',
    festivals: [
      {
        name: 'Mahavir Jayanti',
        date: 'Chaitra Shukla 13',
        month: 'March-April',
        description: 'Celebration at multiple temples on the hill',
      },
    ],
    location: {
      latitude: 24.2,
      longitude: 86.6,
      address: 'Parasnath Hill, Giridih',
      city: 'Shikharji',
      state: 'Jharkhand',
      zipCode: '815301',
    },
    images: [
      'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&h=400&fit=crop',
    ],
    sect: 'Shwetambar',
    type: 'Siddhakshetra',
    facilities: [],
    rating: 4.7,
    reviews: 1324,
    travelDuration: '2-3 days',
  },
  {
    id: 'girnar',
    name: 'Girnar Hills',
    description: 'A group of mountains with many important Jain temples and pilgrimage spots.',
    historicalBackground: 'Girnar temples date back many centuries and are revered by Jains.',
    foundingYear: 900,
    foundingDetails: 'Ancient hill temples with stepped approaches.',
    pratisthaYear: 1000,
    acharya: 'Ancient Acharyas',
    architecture: 'Rock-cut and temple complexes on the hillside.',
    moolnayak: [
      {
        name: 'Neminatha',
        height: 'varies',
        metal: 'Stone',
        year: 1000,
        details: 'Important moolnayak at Girnar',
      },
    ],
    specialFacts: ['Mountain pilgrimage', 'Scenic views', 'Historic inscriptions'],
    poojaTimings: '5:30 AM - 7:30 PM',
    darshanTimings: '5:00 AM - 8:00 PM',
    festivals: [],
    location: {
      latitude: 21.1039,
      longitude: 70.784,
      address: 'Girnar Hills',
      city: 'Junagadh',
      state: 'Gujarat',
      zipCode: '362001',
    },
    images: [
      'https://images.unsplash.com/photo-1505678261036-a3fcc5e884ee?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1533462701944-a01f13c4c89f?w=600&h=400&fit=crop',
    ],
    sect: 'Digambar',
    type: 'Siddhakshetra',
    facilities: [],
    rating: 4.6,
    reviews: 940,
    travelDuration: '1-2 days',
  },
]
